import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

import MetaMaskLogo from '../../public/MetaMask.png';
import CoinbaseLogo from '../../public/Coinbase.png';
import QRCodeLogo from '../../public/QRCode.png';
import MarketplaceLogo from '../../public/Marketplace.png';
import UnityLogo from '../../public/Unity.png';
import ThirdwebLogo from '../../public/Thirdweb.png';
import PlayerImage from '../../public/PlayerLarge.png';

import Feature from '@/components/feature';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/css2?family=Concert+One&family=Press+Start+2P&display=swap" rel="stylesheet" />
      </Head>
      <main className='bg-white'>
        <div className='flex flex-col gap-20'>
          <section className="bg-white text-black mt-[80px]">
            <div className='flex flex-row gap-3 justify-between'>
              <div className='pt-28 flex flex-col font-boogaloo text-xl w-[50%] pl-12 justify-between'>
                <h3>
                  Discover a world of adventure with our latest 2D RPG game that offers a unique and exciting gaming experience. Imagine a beautifully crafted and expansive map with turn-based player versus environment battles, where you can showcase your skills and strategy. And now, you can take it to the next level with our decentralized game that requires only your wallet to connect, giving you the freedom to play and explore at any time.
                </h3>
                What sets our game apart is the integration of blockchain technology, which provides a secure and transparent way to own and trade in-game collectibles as NFTs. Our marketplace provides an opportunity for players to trade their valuable assets, making the gaming experience even more thrilling.
                <h3>
                  With PvP mode on the horizon, the competition is about to heat up. Don't miss out on this opportunity to dive right in and be a part of this exciting new world. Get ready for an unforgettable adventure filled with challenge and reward. Start playing today!
                </h3>
                <section className="bg-white text-black pb-8 pt-4">
                  <h2 className="font-boogaloo text-5xl pb-10">
                    Made with
                  </h2>
                  <div className="flex flex-col gap-10">
                    <div className="flex flex-row gap-6">
                      <Image src={UnityLogo} alt="Unity" width={200} />
                      <Image src={ThirdwebLogo} alt="Unity" width={400} />
                    </div>
                  </div>
                </section>
              </div>
              <div className=''>
                <Image src={PlayerImage} alt="Player" width={800} />
              </div>
            </div>
          </section>

          <section className="bg-white px-[275px] text-black pb-16">
            <h2 className="font-boogaloo text-center text-6xl p-6 pb-12">
              Games have never been this fun and accessible at the same time!
            </h2>
            <div className="flex flex-col gap-14">
              <div className="flex flex-row gap-10">
                <Feature image={MetaMaskLogo} title="MetaMask" description="MetaMask's seamless integration allows for effortless and secure transactions within the game world. Players can easily manage their in-game assets, make purchases etc.." />
                <Feature image={QRCodeLogo} title="QR Code" description="We utilize QR codes as a means of connecting physical collectibles to decentralised gaming. This enhances the gaming experience and allows players to own and trade valuable assets." />
              </div>
              <div className="flex flex-row gap-10">
                <Feature image={CoinbaseLogo} title="Coinbase" description="Coinbase integration in our game has been nothing short of wonderful! Players can now easily buy, sell, and store their in-game assets with the security and reliability of Coinbase." />
                <Feature image={MarketplaceLogo} title="Marketplace" description="Our marketplace lets players to trade collectible items as NFTs. Players can now truly own their prized possessions, adding an extra layer of prestige to their in-game achievements!" />
              </div>
            </div>
          </section>
        </div>


        <section className="container mx-auto text-center py-6 mb-12">
          <h2 className="w-full my-2 text-5xl font-bold leading-tight text-center text-white">
            Call to Action
          </h2>
          <div className="w-full mb-4">
            <div className="h-1 mx-auto bg-white w-1/6 opacity-25 my-0 py-0 rounded-t"></div>
          </div>
          <h3 className="my-4 text-3xl leading-tight">
            Main Hero Message to sell yourself!
          </h3>
          <button className="mx-auto lg:mx-0 hover:underline bg-white text-gray-800 font-bold rounded-full my-6 py-4 px-8 shadow-lg focus:outline-none focus:shadow-outline transform transition hover:scale-105 duration-300 ease-in-out">
            Action!
          </button>
        </section>
      </main>
    </>
  )
}
